#include "mesh_utils.h"

#include <unordered_set>
#include <unordered_map>
#include <algorithm>
#include <random>

#include <JanBenderUtilities/OBJLoader.h>

#include "unordered_array_set_and_map.h"

// Tools
void push_back_if_not_present(std::vector<int>& v, const int value)
{
	if (std::find(v.begin(), v.end(), value) == v.end()) {
		v.push_back(value);
	}
}
double generate_random_double(double l, int seed) {
	// Create a random number generator
	std::random_device rd;
	std::mt19937 gen(seed);
	std::uniform_real_distribution<double> dist(-l, l);

	// Generate a random number between zero and l
	return dist(gen);
}

// ========================================================================================================

double stark::utils::deg2rad(const double deg)
{
	return 2.0 * PI * (deg / 360.0);
}

double stark::utils::rad2deg(const double rad)
{
	return rad * 180.0 / PI;
}

void stark::utils::load_obj(std::vector<Eigen::Vector3d>& out_vertices, std::vector<std::array<int, 3>>& out_triangles, const std::string path)
{
	std::vector<std::array<float, 3>> vertices;
	std::vector<std::array<float, 3>> normals;
	std::vector<std::array<float, 2>> texture_coordinates;
	std::vector<JanBenderUtilities::OBJMeshFaceIndices> faces;
	JanBenderUtilities::OBJLoader::loadObj(path, &vertices, &faces, &normals, &texture_coordinates, { 1.0f, 1.0f, 1.0f });

	out_vertices.reserve(vertices.size());
	for (const std::array<float, 3> &point : vertices) {
		out_vertices.push_back({ (double)point[0], (double)point[1], (double)point[2] });
	}

	out_triangles.reserve(faces.size());
	for (const auto& face : faces) {
		out_triangles.push_back({ face.posIndices[0] - 1, face.posIndices[1] - 1, face.posIndices[2] - 1 });
	}
}

Eigen::Vector3d stark::utils::triangle_normal(const Eigen::Vector3d& p0, const Eigen::Vector3d& p1, const Eigen::Vector3d& p2)
{
	return (p0 - p2).cross(p1 - p2).normalized();
}
double stark::utils::triangle_area(const Eigen::Vector3d& p0, const Eigen::Vector3d& p1, const Eigen::Vector3d& p2)
{
	return 0.5 * (p0 - p2).cross(p1 - p2).norm();
}
double stark::utils::unsigned_tetra_volume(const Eigen::Vector3d& p0, const Eigen::Vector3d& p1, const Eigen::Vector3d& p2, const Eigen::Vector3d& p3)
{
	return (1.0 / 6.0) * ((p1 - p0).cross(p2 - p0)).dot(p3 - p0);
}
double stark::utils::signed_tetra_volume(const Eigen::Vector3d& p0, const Eigen::Vector3d& p1, const Eigen::Vector3d& p2, const Eigen::Vector3d& p3)
{
	return std::abs(unsigned_tetra_volume(p0, p1, p2, p3));
}

void stark::utils::find_node_node_map_simplex(std::vector<std::vector<int>>& output, const int32_t* connectivity, const int32_t n_simplices, const int32_t n_nodes_per_simplex, const int32_t n_nodes)
{
	output.resize(n_nodes);
	for (int simplex_i = 0; simplex_i < n_simplices; simplex_i++) {
		const int begin = n_nodes_per_simplex * simplex_i;
		for (int i = 0; i < n_nodes_per_simplex; i++) {
			const int node_i = connectivity[begin + i];
for (int j = i + 1; j < n_nodes_per_simplex; j++) {
	const int node_j = connectivity[begin + j];
	push_back_if_not_present(output[node_i], node_j);
	push_back_if_not_present(output[node_j], node_i);
}
		}
	}
}
void stark::utils::find_internal_angles(std::vector<std::array<int, 4>>& internal_angles, const std::vector<std::array<int, 3>>& triangles, const int n_nodes)
{
	/*
		For each edge in the triangle mesh, find the 2 nodes that are common neighbors of both edge end-points.
	*/
	internal_angles.clear();
	if (triangles.size() == 0) {
		return;
	}

	std::vector<std::vector<int>> node_node_map;
	find_node_node_map_simplex(node_node_map, &triangles[0][0], (int)triangles.size(), 3, n_nodes);
	for (std::vector<int>& nodes : node_node_map) {
		std::sort(nodes.begin(), nodes.end());  // std::set_intersection assumes sorted
	}

	std::vector<std::array<int, 2>> edges;
	find_edges_from_simplices(edges, triangles, n_nodes);

	std::vector<int> buffer;
	internal_angles.reserve(edges.size());
	for (int edge_i = 0; edge_i < (int)edges.size(); edge_i++) {
		const std::array<int, 2>& edge = edges[edge_i];
		const std::vector<int>& neighs_i = node_node_map[edge[0]];
		const std::vector<int>& neighs_j = node_node_map[edge[1]];
		buffer.clear();
		std::set_intersection(neighs_i.begin(), neighs_i.end(), neighs_j.begin(), neighs_j.end(), std::back_inserter(buffer));
		if (buffer.size() == 2) {
			internal_angles.push_back({ edge[0], edge[1], buffer[0], buffer[1] });
		}
		else if (buffer.size() > 2) {
			std::cout << "Stark error: triangle mesh has edges with more than two incident triangles." << std::endl;
			exit(-1);
		}
	}
}

void stark::utils::extract_surface(std::vector<Eigen::Vector3d>& out_vertices, std::vector<std::array<int, 3>>& out_triangles, std::vector<int>& out_triangle_to_tet_node_map, const std::vector<Eigen::Vector3d>& vertices, const std::vector<std::array<int, 4>>& tets)
{
	out_vertices.clear();
	out_triangles.clear();
	out_triangle_to_tet_node_map.clear();

	/* Code partially generated by ChatGPT 4 */

	// Map to store the occurrence of each face
	utils::unordered_array_map<int, 3, int> face_count;

	for (const auto& tet : tets) {
		// Each tetrahedron has four faces, defined by the following vertex indices
		std::array<std::array<int, 3>, 4> faces = { {
			{{tet[0], tet[1], tet[2]}},
			{{tet[0], tet[1], tet[3]}},
			{{tet[0], tet[2], tet[3]}},
			{{tet[1], tet[2], tet[3]}}
		} };

		for (auto& face : faces) {
			// Sort the vertices of the face to handle orientation
			std::sort(face.begin(), face.end());

			// Count the occurrence of each face
			face_count[face]++;
		}
	}

	// Map to associate old vertex indices to new ones
	std::vector<int> old_to_new_indices(vertices.size(), -1);
	int new_index = 0;

	// Filter the faces that are on the surface and remap their vertices
	for (const auto& item : face_count) {
		if (item.second == 1) { // Surface face
			std::array<int, 3> new_face;
			for (int i = 0; i < 3; ++i) {
				int old_index = item.first[i];
				if (old_to_new_indices[old_index] == -1) {
					old_to_new_indices[old_index] = new_index++;
					out_vertices.push_back(vertices[old_index]);
				}
				new_face[i] = old_to_new_indices[old_index];
			}
			out_triangles.push_back(new_face);
		}
	}

	// Reverse map for output
	out_triangle_to_tet_node_map.resize(out_vertices.size());
	for (int old_index = 0; old_index < (int)old_to_new_indices.size(); old_index++) {
		if (old_to_new_indices[old_index] != -1) {
			const int new_index = old_to_new_indices[old_index];
			out_triangle_to_tet_node_map[new_index] = old_index;
		}
	}
}

void stark::utils::compute_node_normals(std::vector<Eigen::Vector3d>& output, const std::vector<Eigen::Vector3d>& vertices, const std::vector<std::array<int, 3>>& triangles)
{
	output.resize(vertices.size(), Eigen::Vector3d::Zero());
	for (const std::array<int, 3> &triangle : triangles) {
		const Eigen::Vector3d normal = triangle_normal(vertices[triangle[0]], vertices[triangle[1]], vertices[triangle[2]]);
		const double area = triangle_area(vertices[triangle[0]], vertices[triangle[1]], vertices[triangle[2]]);
		output[triangle[0]] += area*normal;
		output[triangle[1]] += area*normal;
		output[triangle[2]] += area*normal;
	}
	for (Eigen::Vector3d& normal : output) {
		normal.normalize();
	}
}
void stark::utils::generate_triangular_grid(std::vector<Eigen::Vector3d>& out_vertices, std::vector<std::array<int, 3>>& out_connectivity, const Eigen::Vector2d& bottom, const Eigen::Vector2d& top, const std::array<int, 2>& n_quads_per_dim, const bool randomize, const double z)
{
	assert(bottom[0] <= top[0] && bottom[1] <= top[1]);

	// Precomputation
	const int nx = n_quads_per_dim[0] + 1;
	const int ny = n_quads_per_dim[1] + 1;
	const int n_points = nx * ny;
	const int n_quadrilaterals = n_quads_per_dim[0] * n_quads_per_dim[1];
	const int n_triangles = 2 * n_quadrilaterals;
	const double dx = (top[0] - bottom[0]) / (double)n_quads_per_dim[0];
	const double dy = (top[1] - bottom[1]) / (double)n_quads_per_dim[1];

	// Points
	/* Correspond to a quadrilateral following the pattern:
			[[0, 0],
			 [0, 1],
			 [1, 0],
			 [1, 1]]

		move y -> move x
	*/
	out_vertices.resize(n_points);
	for (int i = 0; i < nx; i++) {
		for (int j = 0; j < ny; j++) {
			const int idx = ny * i + j;
			out_vertices[idx] = { bottom[0] + i * dx, bottom[1] + j * dy, z };

			if (randomize && i != 0 && i != (nx - 1) && j != 0 && j != (ny - 1)) {
				out_vertices[idx][0] += generate_random_double(dx*0.2, idx);
				out_vertices[idx][1] += generate_random_double(dy*0.2, idx);
			}
		}
	}

	// Connectivity
	/* Corresponds to a splited quadrilateral. Resulting triangles with
	   homogeneous normals
			[[0, 2, 3],
			 [0, 3, 1]]

		The relation between an element "coordinate" in the grid
		and its vertices global indices is:

			node_idx = ny*(ei + ni) + (ej + nj)

		where n_xyz is the number of nodes in the xyz dimension, e_ijk
		is the element "coordinate" in the ijk (grid) dimension and n_ijk
		is the local node "coordinate" within the hexahedron.
	*/
	out_connectivity.clear();
	out_connectivity.reserve(n_triangles);
	int tri_i = 0;
	for (int ei = 0; ei < n_quads_per_dim[0]; ei++) {
		for (int ej = 0; ej < n_quads_per_dim[1]; ej++) {
			int nodes_idx[] = { ny * (ei + 0) + (ej + 0),
							   ny * (ei + 0) + (ej + 1),
							   ny * (ei + 1) + (ej + 0),
							   ny * (ei + 1) + (ej + 1) };

			if (ei % 2 == ej % 2) {
				out_connectivity.push_back({ nodes_idx[0], nodes_idx[2], nodes_idx[3] });
				out_connectivity.push_back({ nodes_idx[0], nodes_idx[3], nodes_idx[1] });
			}
			else {
				out_connectivity.push_back({ nodes_idx[0], nodes_idx[2], nodes_idx[1] });
				out_connectivity.push_back({ nodes_idx[2], nodes_idx[3], nodes_idx[1] });
			}
		}
	}
}
stark::utils::Mesh<3> stark::utils::generate_triangular_grid(const Eigen::Vector2d& bottom, const Eigen::Vector2d& top, const std::array<int, 2>& n_quads_per_dim, const bool randomize, const double z)
{
	Mesh<3> mesh;
	generate_triangular_grid(mesh.vertices, mesh.conn, bottom, top, n_quads_per_dim, randomize, z);
	return mesh;
}
std::array<int, 2> stark::utils::generate_triangular_grid(std::vector<Eigen::Vector3d>& out_vertices, std::vector<std::array<int, 3>>& out_connectivity, const double x_length, const double y_length, const int n_short_side, const bool randomize, const double z)
{
	int nx = 0;
	int ny = 0;
	if (x_length < y_length) {
		nx = n_short_side;
		ny = (int)((y_length/x_length)*(double)nx);
	}
	else {
		ny = n_short_side;
		nx = (int)((y_length/x_length)*(double)ny);
	}
	generate_triangular_grid(out_vertices, out_connectivity, { -0.5*x_length, -0.5*y_length }, { 0.5*x_length, 0.5*y_length }, {nx, ny}, randomize, z);
	return {nx, ny};
}
void stark::utils::generate_tet_grid(std::vector<Eigen::Vector3d>& out_vertices, std::vector<std::array<int, 4>>& out_tets, const Eigen::Vector3d& bottom, const Eigen::Vector3d& top, const std::array<int, 3>& n_quads_per_dim)
{
	assert(bottom[0] <= top[0] && bottom[1] <= top[1] && bottom[2] <= top[2]);

	// Precomputation
	const int nx = n_quads_per_dim[0] + 1;
	const int ny = n_quads_per_dim[1] + 1;
	const int nz = n_quads_per_dim[2] + 1;
	const int n_points = nx * ny * nz;
	const int n_hexas = n_quads_per_dim[0] * n_quads_per_dim[1] * n_quads_per_dim[2];
	const int n_tetras = 12 * n_hexas;
	const double dx = (top[0] - bottom[0]) / (double)n_quads_per_dim[0];
	const double dy = (top[1] - bottom[1]) / (double)n_quads_per_dim[1];
	const double dz = (top[2] - bottom[2]) / (double)n_quads_per_dim[2];

	const int nx_hex = n_quads_per_dim[0];
	const int ny_hex = n_quads_per_dim[1];
	const int nz_hex = n_quads_per_dim[2];

	const double dx_half = 0.5 * dx;
	const double dy_half = 0.5 * dy;
	const double dz_half = 0.5 * dz;

	// Points
	/* Correspond to a hexahedron following the pattern:
			[[0, 0, 0],
				[0, 0, 1],
				[0, 1, 0],
				[0, 1, 1],
				[1, 0, 0],
				[1, 0, 1],
				[1, 1, 0],
				[1, 1, 1]]

		move z -> move y -> move x
	*/
	out_vertices.resize(n_points + n_hexas);
	for (int i = 0; i < nx; i++) {
		for (int j = 0; j < ny; j++) {
			for (int k = 0; k < nz; k++) {
				out_vertices[nz * ny * i + nz * j + k] = { bottom[0] + i * dx, bottom[1] + j * dy, bottom[2] + k * dz };
			}
		}
	}

	// Add the hex center points
	const int center_offset = n_points;
	for (int i = 0; i < nx_hex; i++) {
		for (int j = 0; j < ny_hex; j++) {
			for (int k = 0; k < nz_hex; k++) {
				out_vertices[center_offset + nz_hex * ny_hex * i + nz_hex * j + k] = { bottom[0] + i * dx + dx_half, bottom[1] + j * dy + dy_half, bottom[2] + k * dz + dz_half };
			}
		}
	}

	out_tets.reserve(n_tetras);
	for (int ei = 0; ei < nx_hex; ei++) {
		for (int ej = 0; ej < ny_hex; ej++) {
			for (int ek = 0; ek < nz_hex; ek++) {
				int nodes_idx[] = { nz * ny * (ei + 0) + nz * (ej + 0) + (ek + 0),
									nz * ny * (ei + 0) + nz * (ej + 0) + (ek + 1),
									nz * ny * (ei + 0) + nz * (ej + 1) + (ek + 0),
									nz * ny * (ei + 0) + nz * (ej + 1) + (ek + 1),
									nz * ny * (ei + 1) + nz * (ej + 0) + (ek + 0),
									nz * ny * (ei + 1) + nz * (ej + 0) + (ek + 1),
									nz * ny * (ei + 1) + nz * (ej + 1) + (ek + 0),
									nz * ny * (ei + 1) + nz * (ej + 1) + (ek + 1),
									center_offset + nz_hex * ny_hex * ei + nz_hex * ej + ek };

				if (((ek % 2 == 0) && (ei % 2 == ej % 2)) || ((ek % 2 == 1) && (ei % 2 != ej % 2))) {
					// Front
					out_tets.push_back({ nodes_idx[0], nodes_idx[1], nodes_idx[4], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[1], nodes_idx[5], nodes_idx[4], nodes_idx[8] });
					// Left
					out_tets.push_back({ nodes_idx[0], nodes_idx[2], nodes_idx[1], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[1], nodes_idx[2], nodes_idx[3], nodes_idx[8] });
					// Bottom
					out_tets.push_back({ nodes_idx[0], nodes_idx[4], nodes_idx[6], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[0], nodes_idx[6], nodes_idx[2], nodes_idx[8] });

					// Back
					out_tets.push_back({ nodes_idx[3], nodes_idx[2], nodes_idx[7], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[2], nodes_idx[6], nodes_idx[7], nodes_idx[8] });
					// Right
					out_tets.push_back({ nodes_idx[4], nodes_idx[5], nodes_idx[7], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[4], nodes_idx[7], nodes_idx[6], nodes_idx[8] });
					// Top
					out_tets.push_back({ nodes_idx[1], nodes_idx[3], nodes_idx[5], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[3], nodes_idx[7], nodes_idx[5], nodes_idx[8] });
				}
				else {
					// Front
					out_tets.push_back({ nodes_idx[0], nodes_idx[1], nodes_idx[5], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[0], nodes_idx[5], nodes_idx[4], nodes_idx[8] });
					// Left
					out_tets.push_back({ nodes_idx[0], nodes_idx[3], nodes_idx[1], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[0], nodes_idx[2], nodes_idx[3], nodes_idx[8] });
					// Bottom
					out_tets.push_back({ nodes_idx[0], nodes_idx[4], nodes_idx[2], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[2], nodes_idx[4], nodes_idx[6], nodes_idx[8] });

					// Back
					out_tets.push_back({ nodes_idx[3], nodes_idx[2], nodes_idx[6], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[3], nodes_idx[6], nodes_idx[7], nodes_idx[8] });
					// Right
					out_tets.push_back({ nodes_idx[5], nodes_idx[7], nodes_idx[6], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[5], nodes_idx[6], nodes_idx[4], nodes_idx[8] });
					// Top
					out_tets.push_back({ nodes_idx[1], nodes_idx[3], nodes_idx[7], nodes_idx[8] });
					out_tets.push_back({ nodes_idx[1], nodes_idx[7], nodes_idx[5], nodes_idx[8] });
				}
			}
		}
	}
}
stark::utils::Mesh<4> stark::utils::generate_tet_grid(const Eigen::Vector3d& bottom, const Eigen::Vector3d& top, const std::array<int, 3>& n_quads_per_dim)
{
	Mesh<4> mesh;
	generate_tet_grid(mesh.vertices, mesh.conn, bottom, top, n_quads_per_dim);
	return mesh;
}
void stark::utils::write_VTK(const std::string path, const std::vector<Eigen::Vector3d>& vertices, const std::vector<std::array<int, 3>>& triangles, const bool generate_normals)
{
	vtkio::VTKFile vtk_file;

	if (vertices.size() == 0) {
		vtk_file.write_empty(path);
	}
	else {
		vtk_file.set_points_from_twice_indexable(vertices);
		vtk_file.set_cells_from_twice_indexable(triangles, vtkio::CellType::Triangle);
		if (generate_normals) {
			std::vector<Eigen::Vector3d> normals;
			compute_node_normals(normals, vertices, triangles);
			vtk_file.set_point_data_from_twice_indexable("normals", normals, vtkio::AttributeType::Vectors);
		}
		vtk_file.write(path);
	}
}

std::vector<int> stark::utils::vertices_in_AABB(const std::vector<Eigen::Vector3d>& vertices, const Eigen::Vector3d& bottom, const Eigen::Vector3d& top)
{
	std::vector<int> indices;
	for (int i = 0; i < (int)vertices.size(); i++) {
		const Eigen::Vector3d& p = vertices[i];
		if (bottom[0] <= p[0] && p[0] < top[0] &&
			bottom[1] <= p[1] && p[1] < top[1] &&
			bottom[2] <= p[2] && p[2] < top[2]) {
			indices.push_back(i);
		}
	}
	return indices;
}

void stark::utils::move(std::vector<Eigen::Vector3d>& points, const Eigen::Vector3d& translation)
{
	for (Eigen::Vector3d& point : points) {
		point += translation;
	}
}
void stark::utils::rotate_deg(std::vector<Eigen::Vector3d>& points, const double angle, const Eigen::Vector3d& axis)
{
	Eigen::Matrix3d R = Eigen::AngleAxis<double>(deg2rad(angle), axis.normalized()).toRotationMatrix();
	for (Eigen::Vector3d& point : points) {
		point = R * point;
	}
}
void stark::utils::rotate_deg(std::vector<Eigen::Vector3d>& points, const double angle, const Eigen::Vector3d& axis, const Eigen::Vector3d& pivot)
{
	move(points, -pivot);
	rotate_deg(points, angle, axis);
	move(points, pivot);
}
void stark::utils::scale(std::vector<Eigen::Vector3d>& points, const Eigen::Vector3d& scale)
{
	for (Eigen::Vector3d& point : points) {
		point = scale.cwiseProduct(point);
	}
}
void stark::utils::scale(std::vector<Eigen::Vector3d>& points, const double s)
{
	scale(points, { s, s, s });
}
void stark::utils::mirror(std::vector<Eigen::Vector3d>& points, const int dim, const double pivot)
{
	for (Eigen::Vector3d& point : points) {
		const double dist = point[dim] - pivot;
		point[dim] = pivot - dist;
	}
}
