name: Build linux wheels

on:
  push:
    branches:
      - prerelease/**
  workflow_dispatch:

jobs:
  linux-cp312:
    name: Linux cp312
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
            CIBW_BUILD: cp312-manylinux_x86_64
            CIBW_TEST_COMMAND: >
                python -c "import numpy, pystark; print('numpy', numpy.__version__); print('pystark import OK'); print(pystark.Settings())"
                && python -m pip check

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-cp312
          path: wheelhouse/*.whl