#!/usr/bin/env bash
set -euo pipefail

# Local Linux wheel builder for STARK / pystark.
#
# Usage:
#   scripts/build_wheel_local_linux.sh
#   scripts/build_wheel_local_linux.sh --clean
#
# Optional environment variables:
#   STARK_BUILD_ENV=stark-wheel-build
#   PYTHON_VERSION=3.12
#
# Notes:
#   - Normal runs keep build/ for incremental rebuilds.
#   - Use --clean when you want to verify a fresh build.
#   - This is a local sanity-check script, not the final release builder.
#     Final release wheels should be generated by cibuildwheel in CI.

ENV_NAME="${STARK_BUILD_ENV:-stark-wheel-build}"
PYTHON_VERSION="${PYTHON_VERSION:-3.12}"
FORCE_CLEAN=0

for arg in "$@"; do
    case "$arg" in
        --clean)
            FORCE_CLEAN=1
            ;;
        -h|--help)
            echo "Usage: $0 [--clean]"
            exit 0
            ;;
        *)
            echo "Unknown argument: $arg"
            echo "Usage: $0 [--clean]"
            exit 1
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

echo "== STARK local wheel build =="
echo "Repo:        ${REPO_ROOT}"
echo "Conda env:   ${ENV_NAME}"
echo "Python:      ${PYTHON_VERSION}"
echo "Force clean: ${FORCE_CLEAN}"
echo

# Make conda activation work in non-interactive scripts.
if ! command -v conda >/dev/null 2>&1; then
    echo "Error: conda was not found in PATH."
    echo "Install Miniforge/Miniconda or load conda before running this script."
    exit 1
fi

eval "$(conda shell.bash hook)"

# Create the build-driver environment if needed.
if ! conda env list | awk '{print $1}' | grep -qx "${ENV_NAME}"; then
    echo "Creating conda environment '${ENV_NAME}'..."
    conda create -y -n "${ENV_NAME}" "python=${PYTHON_VERSION}" pip
fi

conda activate "${ENV_NAME}"

echo "Using Python:"
which python
python --version
echo

echo "Installing/updating local build tools..."
python -m pip install --upgrade pip
python -m pip install --upgrade build scikit-build-core twine

echo

if [[ "${FORCE_CLEAN}" == "1" ]]; then
    echo "Cleaning all local build artifacts..."
    rm -rf build dist wheelhouse _skbuild
    rm -rf *.egg-info pystark/*.egg-info pystark/pystark/*.egg-info

    # Remove source-tree extension outputs from previous local builds.
    # These are convenient for development, but should not be trusted as
    # packaging inputs.
    rm -f pystark/pystark/*.so
    rm -f pystark/pystark/*.pyd
    rm -f pystark/pystark/*.dll
    rm -f pystark/pystark/*.dylib
else
    echo "Keeping build/ for incremental rebuilds."
    echo "Cleaning only packaging outputs..."
    rm -rf dist
fi

echo
echo "Building wheel..."

PYTHON_EXECUTABLE="$(python -c 'import sys; print(sys.executable)')"

echo "CMake Python:"
echo "  STARK_PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}"

python -m build --wheel --no-isolation \
    -C"cmake.define.STARK_PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}"

echo
echo "Built wheels:"
ls -lh dist/*.whl

echo
echo "Wheel contents under pystark/:"
python - <<'PY'
import glob
import zipfile
import sys

wheels = glob.glob("dist/*.whl")
if len(wheels) != 1:
    print(f"Expected exactly one wheel in dist/, found {len(wheels)}")
    sys.exit(1)

wheel = wheels[0]
print(wheel)

with zipfile.ZipFile(wheel) as z:
    names = sorted(z.namelist())
    pystark_names = [n for n in names if n.startswith("pystark/")]

    for name in pystark_names:
        print(" ", name)

    has_init = any(n == "pystark/__init__.py" for n in names)
    has_serialize = any(n == "pystark/serialize.py" for n in names)
    has_extension = any(
        n.startswith("pystark/pystark.") and
        (n.endswith(".so") or n.endswith(".pyd") or n.endswith(".dll") or n.endswith(".dylib"))
        for n in names
    )

    print()
    print("Package checks:")
    print("  __init__.py: ", "OK" if has_init else "MISSING")
    print("  serialize.py:", "OK" if has_serialize else "MISSING")
    print("  extension:   ", "OK" if has_extension else "MISSING")

    if not (has_init and has_serialize and has_extension):
        print()
        print("ERROR: wheel is missing required pystark package files.")
        sys.exit(1)
PY

echo
echo "Checking wheel metadata..."
twine check dist/*

echo
echo "Smoke-testing wheel in a clean venv..."
TEST_ROOT="$(mktemp -d /tmp/stark-wheel-test-XXXXXX)"

cleanup() {
    rm -rf "${TEST_ROOT}"
}
trap cleanup EXIT

python -m venv "${TEST_ROOT}/venv"
source "${TEST_ROOT}/venv/bin/activate"

python -m pip install --upgrade pip
python -m pip install dist/*.whl

python - <<'PY'
import pystark

print("pystark import OK")
print("module:", pystark)

# Basic sanity check. Keep this intentionally tiny.
settings = pystark.Settings()
print("Settings object OK:", type(settings))
PY

deactivate

echo
echo "Done."